### ISSUE TITLE
Compile to lua?

### ISSUE THREAD

**Issue by SupinePandora43** [javabird25/PyGmod#4]
how can i compile `.py` to `.lua`?
like python for developing, and lua for production

**Comment by javabird25** [comment]
You might want to take a look at [this Python to Lua translator project](https://github.com/NeonMercury/python-lua), however, this translator has nothing to do with PyGmod.

**Comment by SupinePandora43** [comment]
@javabird25 , use python very powerful for addon developers, but not for stock players
